### PR TITLE
Fix full-screen map when browser is full-screen

### PR DESCRIPTION
**Pull request by gjvoosten**
Fixes brunob/leaflet.fullscreen#121

### CODE REVIEW

**Comment by brunob** [comment]
> @brunob Anything I can do to help get this merged and released?

Thx for the issue and the PR, just let me a couple of days to find a moment to review it.

**Comment by gjvoosten** [comment]
I hate to ask (again), @brunob, but any progress on this?

**Comment by brunob** [comment]
The fix seems good, but i have a doubt on performance impact of calling `invalidateSize()` every times. Any thoughts @BePo65 ?

**Comment by gjvoosten** [comment]
> The fix seems good, but i have a doubt on performance impact of calling `invalidateSize()` every times. Any thoughts @BePo65 ?

Not sure what you mean by "every time". The calls to `invalidateSize()` only happen upon entering full-screen (via the button), and when exiting full-screen (both via the button and via the Escape key).

**Comment by BePo65** [comment]
IMHO @gjvoosten is right: `invalidateSize()` should be triggered only, when the fullscreen state changes. So I do not see any performance penalties.

**Comment by brunob** [comment]
Nice, let's merge this :)

**Comment by brunob** [comment]
published with version 3.0.2, thx again @gjvoosten !

**Pull request merged**
